#!/usr/bin/env bash

HASH_TYPE="${2:-md5}" # md5, sha256, sha1
TARGET="${1:-$HOME/.ssh}"

check_key() {
	# ssh-keygen -l -E "$HASH_TYPE" -f "$KEY_FILE_PATH"
	# echo ssh-keygen -l -E "$HASH_TYPE" -f "$1"
	ssh-keygen -l -E "$HASH_TYPE" -f "$1"
}

eq_line() {
	COLS=$(tput cols)
	WIDTH=0
	LINE=''

	while [ "$WIDTH" -lt "$COLS" ]; do
		LINE="$LINE="
		WIDTH="$((WIDTH+1))"
	done

	printf "\n%s\n" "$LINE"
}

valid_key_file() {
	[ -f "$1" ] && [ -s "$1" ] && [ "$(sed -n '/^ssh-/p;q' "$1")" ]
}

if [ -d "$TARGET" ]; then
	printf "\n%s is a directory\n" "$TARGET"
	printf "$MESSAGE every key in %s/\n" "$TARGET"
	TARGET="$TARGET/*"
elif valid_key_file "$TARGET"; then
	printf "\n%s is a file\n" "$TARGET"
	printf "$MESSAGE %s\n" "$TARGET"
else
	printf "\n%s is not a valid public key file\n" "$TARGET"
	exit 1
fi

eq_line

for path in $TARGET; do
	if ! valid_key_file "$path"; then continue; fi

	printf "fingerprint for %s:\n" "$path"
	fingerprint=$(check_key "$path")
	printf "  %s\n" "$fingerprint"
done
