#!/usr/bin/env bash

# Taken from https://stackoverflow.com/a/246128/771948
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

FILENAME="$( basename "$SOURCE" )"

USAGE="Usage:
  $FILENAME [command] [title]
    opens a new tab with the specified title and runs the specified command inside it"

new_tab() {
	osascript &>/dev/null <<-EOF
	tell application "iTerm2"
		tell current window to set newTab to (create tab with default profile)
		tell current session of newTab to write text "title ${2}"
		tell current session of newTab to write text "${1}"
	end tell
	EOF
}

# App entry point
if [ -z "$TERM_SESSION_ID" ]; then
	echo "Error: Not an iTerm session."
	exit 1
elif [ $# -ne 2 ]; then
	echo "$USAGE"
	exit 1
else
	new_tab "$1" "$2"
fi

exit $?
